server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # none(无应答模式) auto(自动应答模式) manual（手动应答模式）
        acknowledge-mode: auto
  datasource:
      url: jdbc:mysql://localhost:3306/sff?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    # redis 配置
  redis:
        # 地址
        host: localhost
        # 端口，默认为6379
        port: 6379
        # 数据库索引
        database: 0
        # 密码
        password:
        # 连接超时时间
        timeout: 10s
        lettuce:
          pool:
            # 连接池中的最小空闲连接
            min-idle: 0
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池的最大数据库连接数
            max-active: 8
            # #连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1ms
mybatis:
  # 配置mapper.xml文件路径
  mapper-locations: classpath:/mapper/**/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

aliyun:
  AccessKeyId: LTAI5tLKVq1Wvzb8JzdiiVw7
  AccessKeySecret: eabQg4BFuixiUzYXG3CQchTBqumo7A
  SignName: sy990620
  oss:
   endpoint: https://oss-cn-guangzhou.aliyuncs.com
   bucketName: shenfeifan
obs:
  AccessKeyId: MA4PWDW0URWTMOWNHH8K
  AccessKeySecret: 1aO3Uawh3CKrrPTTEh7MhWN4dByBQZ7THdYCpV3Y
  endpoint: https://obs.cn-south-1.myhuaweicloud.com
  bucketName: jxxgmm
# sql日志
logging:
  level:
    # 指定mybatis的mapper映射配置文件的包路径
    com.springboot.mapper: debug
