spring:
  datasource:
   url: jdbc:mysql://127.0.0.1:3306/sff
   username: root
   password:
   driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # 配置mapper.xml文件路径
  mapper-locations: classpath:/mapper/**/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


