server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # none(无应答模式) auto(自动应答模式) manual（手动应答模式）
        acknowledge-mode: auto
  datasource:
      url: jdbc:mysql://rm-cn-g4t3iq168000keoo.rwlb.rds.aliyuncs.com:3306/sff?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: Sy990620
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # 配置mapper.xml文件路径
  mapper-locations: classpath:/mapper/**/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

aliyun:
  AccessKeyId: LTAI5tLKVq1Wvzb8JzdiiVw7
  AccessKeySecret: eabQg4BFuixiUzYXG3CQchTBqumo7A
  SignName: sy990620
  oss:
   endpoint: https://oss-cn-guangzhou.aliyuncs.com
   bucketName: shenfeifan
obs:
  AccessKeyId: MA4PWDW0URWTMOWNHH8K
  AccessKeySecret: 1aO3Uawh3CKrrPTTEh7MhWN4dByBQZ7THdYCpV3Y
  endpoint: https://obs.cn-south-1.myhuaweicloud.com
  bucketName: jxxgmm
# sql日志
logging:
  level:
    # 指定mybatis的mapper映射配置文件的包路径
    com.springboot.mapper: debug
