server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # none(无应答模式) auto(自动应答模式) manual（手动应答模式）
        acknowledge-mode: auto
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sff
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # 配置mapper.xml文件路径
  mapper-locations: classpath:/mapper/**/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

# sql日志
logging:
  level:
    # 指定mybatis的mapper映射配置文件的包路径
    com.springboot.mapper: debug

